apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.1
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            defaultReplicaCount: 3
            defaultDataLocality: disabled
          persistence:
            defaultClass: true
            defaultClassReplicaCount: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
